#!/bin/bash

cd $(dirname "$0")

echo "This will start a postgres docker container. I'll try to stop it when you exit with Ctrl + C.

Press enter key to continue..."

# prompt for input so user can read the message above
read anything

podman-compose up -d
cd $PROJECT_NAME_ELIXIR

# on initial run, create the database
if [ "$1" == "--init" ]; then
  mix ecto.create
fi

mix phx.server
cd ..
podman-compose down

echo "goodbye"
