#!/bin/bash

cd $(dirname "$0")

echo "This will start a postgres docker container. Don't forget to stop it when you're done!

I'll try to stop it when you exit with Ctrl + C, but I just wanted to let you know in case it doesn't stop properly.

Press enter key to continue..."

# prompt for input so user can read the message above
read anything

podman-compose up -d
cd $PROJECT_NAME_ELIXIR

# on initial run, create the database
if [ "$1" == "--init" ]; then
  mix ecto.create
fi

mix phx.server
cd ..
podman-compose down

echo "goodbye"
